language: python
dist: xenial
sudo: false
cache:
  - pip

python:
- 3.6
- 3.7
- 3.8

addons:
  apt:
    packages:
    - graphviz

before_install:
- pip install -U pip

install:
- pip install -e .
- python -c "import uqbar"
- pip install -e .[test]

script:
- ls -l
- make black-check
- make flake8
- if [[ $TRAVIS_PYTHON_VERSION != 3.6 ]]; then make mypy; fi
- make pytest
- make docs

after_success:
- coveralls

notifications:
  email:
    on_success: never
    on_failure: always
